---
- hosts: hector-nodes 
  user: root 
  sudo: yes 

  tasks:

  - name: install Nginx 
    apt: pkg=nginx state=installed   
    notify:
     - Start Nginx

  handlers:
   - name: Start Nginx
     service: name=nginx state=started


   
