---
- hosts: hector-nodes 
  user: root 
  sudo: yes 

  tasks:

  - name: remove packages
    apt: name={{ item }} state=absent
    with_items:
      - git
      - mcrypt
      - nginx
      - php5-cli
      - php5-curl
      - php5-fpm
      - php5-intl
      - php5-json
      - php5-mcrypt
      - php5-sqlite
      - sqlite3
